#!/usr/bin/env zsh

# Session
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=sway
export XDG_CURRENT_DESKTOP=sway

# Wayland stuff
export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland
export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1


# Source zsh specific files
[ -f "$HOME/.zshenv" ] && . "$HOME/.zshenv"
[ -f "$HOME/.zshrc" ] && . "$HOME/.zshrc"

exec sway "$@"
